name: Bug Report
description: Report a bug or issue with DAIRA
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: When I click the post button, nothing happens...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: The post should be created and appear in the feed
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Nothing happens, no error message shown
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of DAIRA is affected?
      options:
        - Web (Frontend)
        - API (Backend)
        - Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: v0.1.0 or commit hash
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        OS: Ubuntu 22.04
        Browser: Chrome 120
        Node: 18.18.0
        Docker: 24.0.6
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Any relevant log output
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots if applicable
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
    validations:
      required: false
